### ISSUE TITLE
form表单RangePicker[showTime]日历选择问题

### ISSUE THREAD

**Issue by xenuxu** [NSFI/ppfish-components#19]
Fom表单，时间类控件中，类型为RangePicker[showTime]的日历，选中的具体日期和展示的日期不一致，比如，我选择1月1日，展示出来的是1月3日

**Comment by yeaaaling** [comment]
format改为"yyyy-MM-dd HH:mm:ss"试试

**Comment by gtopia** [comment]
官网Demo中DatePicker组件的format参数写法有问题，`yyyy-MM-DD`应该为`yyyy-MM-dd`，已修复：https://nsfi.github.io/ppfish-components/#/components/form，感谢反馈。
