### ISSUE TITLE
steps 中 step的icon设置为reactnode不生效

### ISSUE THREAD

**Issue by lunar9621** [NSFI/ppfish-components#25]
<Steps> 
<Step col={<i className="colfont colchuangjian" style={{ marginRight: 5 }}/>} onClick={addProgress}></Step>
</Steps>

预期步骤条图标应显示为自定义iconfont,但没有生效，仍显示为默认圆点

**Comment by gtopia** [comment]
是不是没有设置 font-family ？
我在本地无法复现，能否用[CodeSandbox](https://codesandbox.io/)提供一个可复现的例子？
