### ISSUE TITLE
似乎样式中代码有问题？

### ISSUE THREAD

**Issue by littlerzrz** [NSFI/ppfish-components#49]
./node_modules/_ppfish@1.8.1@ppfish/lib/components/Cascader/style/index.less (./node_modules/_css-loader@4.3.0@css-loader/dist/cjs.js??ref--5-oneOf-8-1!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??postcss!./node_modules/_resolve-url-loader@3.1.2@resolve-url-loader??ref--5-oneOf-8-3!./node_modules/_less-loader@7.3.0@less-loader/dist/cjs.js??ref--5-oneOf-8-4!./node_modules/_ppfish@1.8.1@ppfish/lib/components/Cascader/style/index.less)

        .iconfont-font("\e68c");
        .iconfont-size-under-12px(8px);
      ^
Error evaluating function `unit`: the first argument to unit must be a number. Have you forgotten parenthesis?

**Comment by SummerOverture** [comment]
你好，能详细描述下问题出现的步骤和环境吗？或者能有个复现的demo链接也好。
目前的这个错误智能初步判定为less编译错误。

**Comment by littlerzrz** [comment]
> 你好，能详细描述下问题出现的步骤和环境吗？或者能有个复现的demo链接也好。
> 目前的这个错误只能初步判定为less编译错误。

我在引入富文本编辑器的时候凉的，我不知道其他元素是不是一样，我用的create-react-app，然后其他组件用的antd，所以不知道是不是有冲突？

**Comment by SummerOverture** [comment]
检查下编译的less options? 
http://lesscss.org/usage/#less-options-strict-units

**Comment by SummerOverture** [comment]
> > 你好，能详细描述下问题出现的步骤和环境吗？或者能有个复现的demo链接也好。
> > 目前的这个错误只能初步判定为less编译错误。
> 
> 我在引入富文本编辑器的时候凉的，我不知道其他元素是不是一样，我用的create-react-app，然后其他组件用的antd，所以不知道是不是有冲突？

可以尝试在less-loader的options中添加 lessOptions: { math: 'always' } 试了下是可以正常工作的。
翻阅less文档发现是由于v3和v4中的math默认属性不一致导致的bug http://lesscss.org/usage/#less-options-math
