### ISSUE TITLE
表格无 table-header设置API，业务需求中需要总计放在顶部，现通过第一条记录标识为总计，存在分页问题，希望该场景能有更合适的 API 支持

### ISSUE THREAD

**Issue by omamzhang** [NSFI/ppfish-components#52]
@hepeguo 
**兼容方案**：  通过异步方式加载数据，分页数据请求增加一条总计数据，当前页数据为： pageSize+1， 则导致当前页数据展示少一条，这在预期内；
**方案问题**：后续分页将展示“无数据” 实际有数据传递。
**希望**：支持table-header API 或者，对兼容方案的场景可以处理一下。

**兼容方案代码示例**（结合console 与界面表现一起查看）[基于远程加载数据案例](https://nsfi.github.io/ppfish-components/#/components/table)：
` constructor() {
    super();
    this.state = {
      data: [],
      pagination: {},
      loading: false,
    }
  }

  handleTableChange = (pagination, filters, sorter) => {
    const pager = { ...this.state.pagination };
    pager.current = pagination.current;
    this.setState({
      pagination: pager,
    });
    this.fetch({
      results: pagination.pageSize,
      page: pagination.current,
      sortField: sorter.field,
      sortOrder: sorter.order,
      ...filters,
    });
  }
  i=0;
  fetch = (params = {}) => {
    console.log('params:', params);
    this.setState({ loading: true });
      ++this.i;
    fetch('https://randomuser.me/api?results=10').then((res) => {
      return res.json() 
    }).then((data) => {
      const pagination = { ...this.state.pagination };
      // Read total count from server
      // pagination.total = data.totalCount;
      let { results }  = data;
      results = (results || []).map(itm => { 
              itm.email += `_${this.i}`;
              return itm; }),
      console.log(results[0]&&results[0].email);
      pagination.total = 200; 
      this.setState({
        loading: false,
        data: results,
        pagination,
      });
    });
  }

  componentDidMount() {
    this.fetch();
  }
  i=0;
  j=0;
  render() {
    const columns = [{
      title: 'Name',
      dataIndex: 'name',
      sorter: true,
      render: name => `${name.first} ${name.last}`,
      width: '20%',
    }, {
      title: 'Gender',
      dataIndex: 'gender',
      filters: [
        { text: 'Male', value: 'male' },
        { text: 'Female', value: 'female' },
      ],
      width: '20%',
    }, {
      title: 'Email',
      dataIndex: 'email',
    }];
    let { pagination, data }  =  this.state;
    pagination.pageSize = 2;
    ++this.j;
    const dataList = data.map(itm => { 
		itm.email  += `_${this.j}`;
 		return itm;
    });
    console.log(data[0]&&data[0].email, dataList[0]&&dataList[0].email);

    return (
      <Table
        columns={columns}
        rowKey={record => record.login.uuid}
        dataSource={dataList}
        pagination={pagination}
        loading={this.state.loading}
        onChange={this.handleTableChange}
      />
    );
  }`

**Comment by SummerOverture** [comment]
可以提个pr~
