### ISSUE TITLE
富文本 使用 customInsertImage 插入图片

### ISSUE THREAD

**Issue by GDLong** [NSFI/ppfish-components#56]
customInsertImage 只有一个callback，点击上传图片直接进入方法，并没有弹出上传图片的框？咋回事！

**Comment by gtopia** [comment]
customInsertImage 接口用于自定义上传图片，接收一个图片上传函数（里面的上传逻辑要自己写），该函数有一个callback参数，上传完图片后需要通过callback参数把图片信息回传。可以参考下官网中『自定义插入图片』那个demo：
https://nsfi.github.io/ppfish-components/#/components/richEditor

**Comment by zactony** [comment]
官网的 Demo 只是展示了如何将上传好后的图片 URL 展示在富文本编辑器里面，但是，在此之前开发者如何获取到上传的 File 对象然后自定义上传？

**Comment by iamyushan** [comment]
> 官网的 Demo 只是展示了如何将上传好后的图片 URL 展示在富文本编辑器里面，但是，在此之前开发者如何获取到上传的 File 对象然后自定义上传？

请问解决了吗

**Comment by gtopia** [comment]
上传逻辑需要使用方在组件外实现，可以使用一个隐藏的Input获取File，跟普通的文件上传一样。
