### ISSUE TITLE
RichEditor 组件编辑内容，渲染问题

### ISSUE THREAD

**Issue by ceser-x** [NSFI/ppfish-components#65]
业务描述：
通过RichEditor组件，编辑了富文本内容。系统发送富文本内容到邮箱，样式异常。
当前状态：
已经引入了quill的css文件
`import 'react-quill/dist/quill.core.css';`
当前样式还是有问题，例如<blockquote>、<pre class="ql-syntax">这些标签还是渲染错误。还依赖其他的css文件吗？

富文本样式：
<img width="923" alt="111" src="https://user-images.githubusercontent.com/32259724/141966937-834d8476-cd5b-45e7-9995-e5ab523129f8.png">
<img width="908" alt="222222" src="https://user-images.githubusercontent.com/32259724/141966963-1d82dc87-6f7c-41a8-b36d-d270f3c0de29.png">

展示样式是自己写了一个div，加了ql-editor的类名：
<img width="999" alt="333" src="https://user-images.githubusercontent.com/32259724/141968249-5b13195b-a37a-40f0-92d3-99af99b6b722.png">

部分标签展示异常，请教一下，怎么处理？

**Comment by gtopia** [comment]
需要引用ppfish提供的样式`import 'ppfish/dist/ppfish.min.css';`
