### ISSUE TITLE
RichEditor 富文本编辑器  自定义插入图片 不能获取到图片对象

### ISSUE THREAD

**Issue by iamyushan** [NSFI/ppfish-components#70]
在配置自定义插入图片的时候 

![image](https://user-images.githubusercontent.com/29141080/144550625-36cd709e-0807-4371-af7b-cc27e8820fba.png)

开发者如何获取图片对象 实现自定义上传 然后callback() 呢。getImageUrl 参数里并没有 file 对象。只有一个 callback。

**Comment by iamyushan** [comment]
升级到 2.0.0-alpha.3 版本问题依然存在。

**Comment by gtopia** [comment]
这不是bug，参考https://github.com/NSFI/ppfish-components/issues/56

**Comment by iamyushan** [comment]
意思是  走默认的图片上传  会转为 dataUrl 的格式插入。如果走自定义图片上传  应该先通过 onClickToolbarBtn 判断是否点击图片按钮  然后 insertImageModalVisible 设置为 false  然后自己实现弹窗实现图片上传到服务器。最后再调用 customInsertImage 的 callback 实现 src 的替换。

既然这样的话  如果设置了 customInsertImage 那么 insertImageModalVisible 默认为 false 会不会更好一些。减少理解的成本。

**Comment by gtopia** [comment]
如果customInsertImage不为空，点击「选择本地图片」时，就会调用customInsertImage，然后开发者需要在customInsertImage中实现上传文件的逻辑，跟onClickToolbarBtn和insertImageModalVisible没有关系。
![image](https://user-images.githubusercontent.com/8113851/144561114-5e161beb-f4f5-42c6-8f5b-4ebdcdadc445.png)

**Comment by iamyushan** [comment]
你好。绑定的函数在点选择本地图片后会调用。但是调用后 file 我们拿不到  怎么去上传呢。如果我们自己去实现这个上传弹窗 现在的问题是  点toolbar的图片按钮  就会调用customInsertImage。然后弹出我们自己写的弹窗  上传完图片后  就没办法再次调用customInsertImage。

是我哪里理解有问题吗  有点绕进去了。

**Comment by iamyushan** [comment]
> 如果customInsertImage不为空，点击「选择本地图片」时，就会调用customInsertImage，然后开发者需要在customInsertImage中实现上传文件的逻辑，跟onClickToolbarBtn和insertImageModalVisible没有关系。 ![image](https://user-images.githubusercontent.com/8113851/144561114-5e161beb-f4f5-42c6-8f5b-4ebdcdadc445.png)

你好。绑定的函数在点选择本地图片后会调用。但是调用后 file 我们拿不到 怎么去上传呢。如果我们自己去实现这个上传弹窗 现在的问题是 点toolbar的图片按钮 就会调用customInsertImage。然后弹出我们自己写的弹窗 上传完图片后 就没办法再次调用customInsertImage。

是我哪里理解有问题吗 有点绕进去了。

**Comment by iamyushan** [comment]
![image](https://user-images.githubusercontent.com/29141080/144563150-cbcbb916-9980-4980-96df-79cbd76794ac.png)

像自定义拖入/粘贴图片 绑定的函数参数文档里说有两个 其中一个就是 files  但实际使用没有返回

**Comment by gtopia** [comment]
使用customInsertImage后，文件上传就跟组件没有关系了，整个文件上传逻辑要使用方实现，组件要的只是文件上传后的URL，上传完成后通过customInsertImag的第二个参数把文件URL回传给组件就可以。

**Comment by gtopia** [comment]
![image](https://user-images.githubusercontent.com/8113851/144564154-3c8cb08b-4970-4dec-8d7a-3481222bd71b.png)
你demo看错了，自定义上传图片要看这个demo。

**Comment by iamyushan** [comment]
> 使用customInsertImage后，文件上传就跟组件没有关系了，整个文件上传逻辑要使用方实现，组件要的只是文件上传后的URL，上传完成后通过customInsertImag的第二个参数把文件URL回传给组件就可以。

是的  可是选择本地图片弹窗  是框架提供的  但是没返回 file  我们怎么能拿到这个file

**Comment by gtopia** [comment]
自己百度一下如何用JS上传文件吧。

**Comment by iamyushan** [comment]
我们知道怎么上传文件啊  这个点击动作 是点击你们的富文本编辑器不是吗。你的意思是 这个图片按钮  不能用。我们需要自己在其他地方写一个  拿到文件  然后去 callback 替换 url？

![image](https://user-images.githubusercontent.com/29141080/144564540-d0a578af-1a62-4dbc-a397-f0f1096577be.png)

**Comment by iamyushan** [comment]
自定义拖入/黏贴图片就会返回给开发者 file  
自定义插入就不返回
原因是啥呢

![image](https://user-images.githubusercontent.com/29141080/144566388-8124f504-ce9a-4bca-baf9-a65effcf623b.png)
