### ISSUE TITLE
PicturePreview 在切换路由时报错

### ISSUE THREAD

**Issue by zuiidea** [NSFI/ppfish-components#8]
react 版本 `16.8.4`
react-router 版本 `4.3.1`

报错信息：
```
react-dom.development.js:9254 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
```
index.js:1446 The above error occurred in the <Route> component:
```

猜测原因：
PicturePreview的dom节点挂载到documen.body上

建议解决方案：

PicturePreview的dom节点不要挂载到documen.body上，
或者可新增参数自定义挂载节点

[相关代码 ](https://github.com/NSFI/ppfish-components/blob/master/source/components/PicturePreview/index.js) 123行

```
document.body.appendChild(mask ? this.$root : this.$el);
```

**Comment by gtopia** [comment]
@zuiidea hi，我在本地没有复现你描述的问题，方便用 codesandbox 创建一个在线可复现环境吗？另外，看报错信息提示的是执行 'removeChild' 时出错，是否是你业务代码中的问题呢？

**Comment by zuiidea** [comment]
- 在`codeSandbox`没有复现出切换路由报错，可能跟本地环境有关，本地环境有点复杂，不太好搭建。

- 发现另外的问题，无法切换下一张或者上一张，
复现地址：
[https://codesandbox.io/s/m7z439y82p](https://codesandbox.io/s/m7z439y82p)

修复建议：
```
  if (activeIndex !== current) {
      newState['current'] = activeIndex
  }
```
to
```
  if (activeIndex !== current && !show) {
      newState['current'] = activeIndex
  }
```

- 强烈建议使用`React`的`createPortal`来优化这个组件，并减少dom的操作。

**Comment by gtopia** [comment]
@zuiidea 非常感谢你反馈的问题，尤其是提供的 `codeSandbox` 在线复现环境，对我们定位问题很有帮助！
我们在已经发布的 `ppfish 1.6.9-rc.1` 中修复了 `PicturePreview` 的以下问题：
1. 组件 `unmount` 时未正常移除挂载节点
2. 使用 `React.lazy` 对组件做懒加载时，无法正常切换图片
当前版本的 `PicturePreview` 中没有使用 `React` 的 `createPortal` ，会考虑在后续的版本中加入。
