### ISSUE TITLE
RichEditor组件 有生成目录，链接相关内容的功能么，类似word里的？

### ISSUE THREAD

**Issue by pxim** [NSFI/ppfish-components#84]
类似这样
![image](https://user-images.githubusercontent.com/5111701/157192828-7651c4cc-d6d8-46b5-b784-2f476e18f637.png)

**Comment by gtopia** [comment]
RichEditor目前没有自动生成目录的功能，暂时还没有支持此功能的计划，可以尝试使用项目符号和缩进手动编写目录。
