### ISSUE TITLE
safari下富文本RichEditor无法输入

### ISSUE THREAD

**Issue by sunshine541** [NSFI/ppfish-components#85]
"ppfish": "^1.7.3",
安装版本：      "_id": "ppfish@1.8.3",
试过2.0.0版本，在safari下RichEditor也无法编辑
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/23209123/159876230-6805d349-6255-4ab4-850c-58eb692fb992.png">
safari浏览器下，点击红色区域无法获取光标，无法输入

**Comment by gtopia** [comment]
We will fix this issue in the next release. 

If you want a quick fix for this, you can temporarily override the class style of `ql-editor` with `-webkit-user-select: auto;`.
